{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kubevirt-aie-webhook.fullname" . }}-selfsigned
  namespace: {{ include "kubevirt-aie-webhook.namespace" . }}
  labels:
    {{- include "kubevirt-aie-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
