apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt-aie-webhook.fullname" . }}
  namespace: {{ include "kubevirt-aie-webhook.namespace" . }}
  labels:
    {{- include "kubevirt-aie-webhook.labels" . | nindent 4 }}
