apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubevirt-aie-webhook.fullname" . }}
  namespace: {{ include "kubevirt-aie-webhook.namespace" . }}
  labels:
    {{- include "kubevirt-aie-webhook.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: https
  selector:
    {{- include "kubevirt-aie-webhook.selectorLabels" . | nindent 4 }}
